import type { Metadata } from "next";
import { M_PLUS_Rounded_1c } from "next/font/google";
import "./globals.css";



const textFnt = M_PLUS_Rounded_1c({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ひょうたんひょうん",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${textFnt.className}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
